DROP TABLE IF EXISTS choices CASCADE;

CREATE TABLE choices (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT DEFAULT '',
  choice_id INTEGER REFERENCES choices(id) ON DELETE CASCADE
);
