DROP TABLE IF EXISTS choices CASCADE;

CREATE TABLE choices (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT DEFAULT '',
  poll_id VARCHAR(255) REFERENCES polls(id) ON DELETE CASCADE
);
